config/routes.rb
Rails.application.routes.draw do
  get 'posts/show'

  get 'posts/index'

  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def index
    @post = current_user.posts
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end
  
  def edit
  	@post = Post.find(params[:id])
		if @post.user_id == current_user.id
			# ...
		else
			redirect_to root_path, :notice => "You dont have access to this post."
		end
  end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post
		else
			render "edit"
		end
	end

	def destroy
		if @post.user_id == current_user.id
			#go delete!
		else
			redirect_to root_path, :notice => "You dont have access to this post."
		end
		@post.destroy
		redirect_to posts_path
	end
	
	private

	def post_params
		params.require(:post).permit(:content, :featured_posts)
	end

	def find_post
		@post = Post.find(params[:id]) rescue nil
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    def index
        @posts = Post.where(featured_posts: true)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Your posts', posts_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Myapp" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<div class="container-fluid">
    <%= simple_form_for(@post, html: { class: "form-horizontal"}) do |p| %>
    <%= p.input :content, label: "Content", required: true %>
    <%= p.input :featured_posts, as: :boolean, checked_value: true, unchecked_value: false %>
    <div class="form-actions">
        <%= p.submit "Submit" , class: "btn btn-primary" %>
        <%= link_to "Back", posts_path, class: "btn btn-primary" %>
    </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<h5>Your posts</h5>
<div class="container-fluid">
	<% @post.each do |p| %>
		<p><%= p.content %></p>
		<button type="button" class="btn btn-default btn-xs"><%= link_to "Edit", edit_post_path(p)%></button>
	<% end %>
</div>
<br>
<br>
<div class="form-actions"> 
	<%= link_to "Add new post", new_post_path, class: "btn btn-primary" %>
</div>

app/views/posts/new.html.erb
<h2> New Post:</h2>
<div class="container-fluid">
    <%= simple_form_for(@post, html: { class: "form-horizontal"}) do |f| %>
    <%= f.input :content, label: "Content", required: true %>
    <%= f.input :featured_posts, as: :boolean, checked_value: true, unchecked_value: false %>
    <div class="form-actions">
    <%= f.submit "Submit" , class: "btn btn-primary" %>
    <%= link_to "Back", posts_path, class: "btn btn-primary" %>
    </div>
    <%end%>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
<p><%= @post.content %></p>
<div type="button" class="btn btn-default"><%= link_to "Edit", edit_post_path(@post)%></div>
<div type="button" class="btn btn-default"><%= link_to "Back", posts_path%></div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome to my blog!</h3>
<h2>Featured Posts:</h2>
<div class="container-fluid">
	<% @posts.each do |p| %>
		<div class="container-fluid">
			<p><%= p.content %></p>
			<small>Written by: <%= User.find(p.user_id).name %></small>
			<p><div type="button" class="btn btn-default btn-xs"><%= link_to "View", post_path(p)%></div>
		</div>
	<% end %>
</div>
<br>
<p>This blog have <%= link_to "#{Post.count} posts", posts_path %> written by <%= link_to "#{User.count} users.", users_path %></p>